#pragma once

#include "SyntaxConfig.h"

#include "AccessModifierSyntax.h"
#include "ArgumentSyntax.h"
#include "BinaryOpSyntaxKind.h"
#include "ClassDeclSyntax.h"
#include "ClassMemberDeclSyntaxes.h"
#include "EmbeddableStmtSyntaxes.h"
#include "EnumDeclSyntax.h"
#include "ExpSyntaxes.h"
#include "ForStmtInitializerSyntaxes.h"
#include "FuncParamSyntax.h"
#include "GlobalFuncDeclSyntax.h"
#include "NamespaceDeclSyntax.h"
#include "NamespaceDeclSyntaxElements.h"
#include "ScriptSyntax.h"
#include "ScriptSyntaxElements.h"
#include "StmtSyntaxes.h"
#include "StringExpSyntaxElements.h"
#include "StructDeclSyntax.h"
#include "StructMemberDeclSyntaxes.h"
#include "Tokens.h"
#include "TypeDeclSyntax.h"
#include "TypeExpSyntaxes.h"
#include "TypeParamSyntax.h"
#include "UnaryOpSyntaxKind.h"
#include "VarDeclSyntax.h"

