#include "pch.h"

#include "Syntax/Tokens.h"

#include "Syntax/AccessModifierSyntax.h"
#include "Syntax/ArgumentSyntax.h"
#include "Syntax/BinaryOpKindSyntax.h"
#include "Syntax/ClassDeclSyntax.h"
#include "Syntax/ClassMemberDeclSyntaxes.h"
#include "Syntax/EnumDeclSyntax.h"
#include "Syntax/ExpSyntaxes.h"
#include "Syntax/ForStmtInitializerSyntaxes.h"
#include "Syntax/FuncParamSyntax.h"
#include "Syntax/GlobalFuncDeclSyntax.h"
#include "Syntax/NamespaceDeclSyntax.h"
#include "Syntax/NamespaceElementSyntaxes.h"
#include "Syntax/ScriptSyntax.h"
#include "Syntax/ScriptElementSyntaxes.h"
#include "Syntax/StmtSyntaxes.h"
#include "Syntax/StringExpElementSyntaxes.h"
#include "Syntax/StructDeclSyntax.h"
#include "Syntax/StructMemberDeclSyntaxes.h"
#include "Syntax/TypeDeclSyntax.h"
#include "Syntax/TypeExpSyntaxes.h"
#include "Syntax/TypeParamSyntax.h"
#include "Syntax/UnaryOpKindSyntax.h"
#include "Syntax/VarDeclSyntax.h"
