#include "pch.h"

#include "Syntax/Token.h"

#include "Syntax/AccessModifier.h" 
#include "Syntax/Argument.h"
#include "Syntax/BinaryOpKind.h"
#include "Syntax/ClassDecl.h"
#include "Syntax/ClassMemberDecls.h" 
#include "Syntax/EnumDecl.h" 
#include "Syntax/Exps.h" 
#include "Syntax/ForStmtInitializers.h" 
#include "Syntax/FuncParam.h" 
#include "Syntax/GlobalFuncDecl.h" 
#include "Syntax/NamespaceDecl.h" 
#include "Syntax/NamespaceElements.h" 
#include "Syntax/Script.h" 
#include "Syntax/ScriptElements.h" 
#include "Syntax/Stmts.h" 
#include "Syntax/StringExpElements.h" 
#include "Syntax/StructDecl.h" 
#include "Syntax/StructMemberDecls.h" 
#include "Syntax/TypeDecl.h" 
#include "Syntax/TypeExps.h"
#include "Syntax/TypeParam.h" 
#include "Syntax/UnaryOpKind.h" 
#include "Syntax/VarDecl.h"